/*
 * SPDX-License-Identifier: BSD-3-Clause
 *
 * Pico SDK board definition for the Fightpad 12 Slim RP2350B.
 */

// -----------------------------------------------------
// NOTE: THIS HEADER IS ALSO INCLUDED BY ASSEMBLER SO
//       SHOULD ONLY CONSIST OF PREPROCESSOR DIRECTIVES
// -----------------------------------------------------

#ifndef _BOARDS_FIGHTPAD12SLIM_H
#define _BOARDS_FIGHTPAD12SLIM_H

// pico_cmake_set PICO_PLATFORM=rp2350

#define FIGHTPAD12SLIM

// --- RP2350 VARIANT ---
#define PICO_RP2350A 0
#define PICO_RP2350B 1

// --- BOARD PIN ALIASES ---
#define FIGHTPAD12SLIM_OLED_SDA_PIN 0
#define FIGHTPAD12SLIM_OLED_SCL_PIN 1
#define FIGHTPAD12SLIM_VBUS_DET_PIN 21
#define FIGHTPAD12SLIM_BUTTON_LEDS_PIN 22
#define FIGHTPAD12SLIM_STATUS_LED_PIN 23
#define FIGHTPAD12SLIM_BOOST_EN_PIN 24
#define FIGHTPAD12SLIM_USB_HOST_DPLUS_PIN 28
#define FIGHTPAD12SLIM_USB_HOST_DMINUS_PIN 29
#define FIGHTPAD12SLIM_AMBIENT_ONOFF_PIN 30
#define FIGHTPAD12SLIM_AMBIENT_PREV_PIN 31
#define FIGHTPAD12SLIM_AMBIENT_NEXT_PIN 32
#define FIGHTPAD12SLIM_TRANSPORT_SEL_PIN 33
#define FIGHTPAD12SLIM_ESP_EN_PIN 34
#define FIGHTPAD12SLIM_ESP_BOOT_PIN 35
#define FIGHTPAD12SLIM_ESP_UART_TX_PIN 36
#define FIGHTPAD12SLIM_ESP_UART_RX_PIN 37
#define FIGHTPAD12SLIM_ESP_UART_CTS_PIN 38
#define FIGHTPAD12SLIM_ESP_UART_RTS_PIN 39
#define FIGHTPAD12SLIM_AMBIENT_LEDS_PIN 40
#define FIGHTPAD12SLIM_VBAT_SENSE_PIN 41
// RP2350B maps GPIO40..47 to ADC0..ADC7, so GP41 is ADC1.
#define FIGHTPAD12SLIM_VBAT_ADC_CHANNEL 1

// --- UART ---
#ifndef PICO_DEFAULT_UART
#define PICO_DEFAULT_UART 0
#endif
#ifndef PICO_DEFAULT_UART_TX_PIN
#define PICO_DEFAULT_UART_TX_PIN 0
#endif
#ifndef PICO_DEFAULT_UART_RX_PIN
#define PICO_DEFAULT_UART_RX_PIN 1
#endif

// --- LED ---
#ifndef PICO_DEFAULT_LED_PIN
#define PICO_DEFAULT_LED_PIN FIGHTPAD12SLIM_STATUS_LED_PIN
#endif
#ifndef PICO_DEFAULT_WS2812_PIN
#define PICO_DEFAULT_WS2812_PIN FIGHTPAD12SLIM_BUTTON_LEDS_PIN
#endif

// --- I2C ---
#ifndef PICO_DEFAULT_I2C
#define PICO_DEFAULT_I2C 0
#endif
#ifndef PICO_DEFAULT_I2C_SDA_PIN
#define PICO_DEFAULT_I2C_SDA_PIN FIGHTPAD12SLIM_OLED_SDA_PIN
#endif
#ifndef PICO_DEFAULT_I2C_SCL_PIN
#define PICO_DEFAULT_I2C_SCL_PIN FIGHTPAD12SLIM_OLED_SCL_PIN
#endif

// --- FLASH ---
#define PICO_BOOT_STAGE2_CHOOSE_W25Q080 1

#ifndef PICO_FLASH_SPI_CLKDIV
#define PICO_FLASH_SPI_CLKDIV 2
#endif

#ifndef PICO_FLASH_SIZE_BYTES
#define PICO_FLASH_SIZE_BYTES (16 * 1024 * 1024)
#endif

// --- USB / POWER SENSE ---
#ifndef PICO_VBUS_PIN
#define PICO_VBUS_PIN FIGHTPAD12SLIM_VBUS_DET_PIN
#endif

#ifndef PICO_RP2350_A2_SUPPORTED
#define PICO_RP2350_A2_SUPPORTED 1
#endif

#endif
